version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=vpn unlimited
      - OPENVPN_USER=richardgetziii@gmail.com
      - OPENVPN_PASSWORD=ATIFKVsBpO06
      - SERVER_HOSTNAMES=us-ny.vpnunlimitedapp.com
      - TZ=America/New_York
    volumes:
      - /volume1/docker/gluetun:/gluetun
    # sysctls:
      #- net.ipv6.conf.all.disable_ipv6=1
    restart: unless-stopped
    ports:
      #- 49162:9117
      - 49077:6077
      - 49004:5004
      #- 49165:6500
  cabernet:
    image: cabernet-vpn:latest
    container_name: cabernet-vpn
    network_mode:
      "service:gluetun"
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    environment:
      - TZ=America/New_York
    volumes:
      - /volume1/docker/cabernet/data:/app/data/
      
    restart: unless-stopped